[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "liteclass"
version = "0.0.1"
authors = [
  { name="sau1707", email="lsaurwein@ethz.ch" },
]
description = "A decorator to match python class to sqllite"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Sau1707/liteclass"
"Bug Tracker" = "https://github.com/Sau1707/liteclass/issues"