name: Publish on PyPI

on:
    push:
        branches:
            - main

jobs:
    pypi:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Bump version
              run: python3 -m pip install toml requests && python3 version.py

            - name: Install dependencies and build
              run: python3 -m pip install --upgrade build && python3 -m build

            - name: Publish package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
